services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
# postgres docker setup
